### ISSUE TITLE
Update requires list, add docs

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk.php#34]
![image](https://user-images.githubusercontent.com/15259299/126984711-600778c8-810c-4d77-b2d5-d88bbfbae220.png)

cannot use latest version on php7.1

![image](https://user-images.githubusercontent.com/15259299/126984787-fdb85372-8634-4c5a-9a50-d4449b55cac0.png)

**Comment by neSpecc** [comment]
Resolved by #56
