### ISSUE TITLE
php 8.1 is not working

### ISSUE THREAD

**Issue by dentelis** [codex-team/hawk.php#53]
Warning: The magic method Hawk\HawkCatcher::__sleep() must have public visibility in vendor\codex-team\hawk.php\src\Hawk.php on line 313

Warning: The magic method Hawk\HawkCatcher::__wakeup() must have public visibility in vendor\codex-team\hawk.php\src\Hawk.php on line 314

Deprecated: ErrorException::__construct(): Passing null to parameter #3 ($severity) of type int is deprecated in vendor\codex-team\hawk.php\src\Hawk.php on line 202

**Comment by khaydarov** [comment]
Hi @dentelis!
Could you provide details how did you installed catcher? The newest version of catcher (v2.1.9) doesn't contain HawkCatcher class

**Comment by neSpecc** [comment]
Resolved by #56
