### ISSUE TITLE
Error: Array to string converstion

### ISSUE THREAD

**Issue by evaleries** [codex-team/hawk.php#55]
Hello,

I'm getting an error when using this package.
Currently, I'm using Laravel 8 and PHP 7.4

Here's my snippet code

```php
try {
  Catcher::get()
      ->sendException($exception, ['version' => config('amf.version'), 'env' => config('app.env')]);

} catch (Exception $e) {
    Log::error($e->getMessage());
}
```

The `$exception` variable is an Exception instance. The problem still occurs even without a context.

Here's the detailed log:
```
local.ERROR: Array to string conversion . 
<br>file:  /Users/redacted/vendor/codex-team/hawk.php/src/Transport/CurlTransport.php 
<br>line: 56 
```

I think because we're trying to send an array using curl from this [line](https://github.com/codex-team/hawk.php/blob/master/src/Transport/CurlTransport.php#L56).
```php
curl_setopt($curl, CURLOPT_POSTFIELDS, $event->jsonSerialize());
```

My working solution:
```php
curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($event->jsonSerialize()));
```

**Comment by neSpecc** [comment]
Resolved by #58
